name: Deploy Hanzagu Image
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
  AUTH_URI: ${{ secrets.AUTH_URI }}
  CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  TOKEN_URI: ${{ secrets.TOKEN_URI }}
  TYPE: ${{ secrets.TYPE }}
  UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
  SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
  SHEET_NAME: ${{ secrets.SHEET_NAME }}
  START_CELL: ${{ secrets.START_CELL }}
  END_CELL: ${{ secrets.END_CELL }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: Hanzagu
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./
            tags: hanzagu

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ matrix.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AUTH_PROVIDER_X509_CERT_URL
            AUTH_URI
            CLIENT_EMAIL
            CLIENT_ID
            CLIENT_X509_CERT_URL
            PRIVATE_KEY
            PRIVATE_KEY_ID
            PROJECT_ID
            TOKEN_URI
            TYPE
            UNIVERSE_DOMAIN
            SPREADSHEET_ID
            SHEET_NAME
            START_CELL
            END_CELL
